[package]
name = "quail"
version = "0.1.0"
authors = ["Michael Maloney"]
edition = "2018"
description = "The Quail Programming Language"
license = "BSD-2-Clause"

[dependencies]
rustyline = "5.0.5"
dirs = "2.0.1"
structopt = "0.3.5"
